#!/bin/csh
#
echo  perform AM1 optimization
#
# usage - xAM1OPT moleculename
#
# test if the enviroment variable BOSSdir has been defined
#
if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

if (-e optzmat) rm optzmat
cp ${argv[1]}.z optzmat
csh $BOSSdir/scripts/AM1OPTcmd >& log
rm optzmat
echo  output is in out, sum and plt.pdb
grep "Optimized en" out
echo =Heat of Formation
#
exit
