#!/bin/csh
#
echo  perform single-point AM1 calculation
echo  generate AM1-LBCC charges
#
# usage - xAM1SPL moleculename
#
# test if the enviroment variable BOSSdir has been defined
#
if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

if (-e optzmat) rm optzmat
cp ${argv[1]}.z optzmat
csh $BOSSdir/scripts/AM1SPLcmd >& log
echo  output is in out, sum and plt.pdb
#
exit
