#!/bin/csh
# set echo
#
# generate separate .mol files
#
# usage - xCSMOL
#
# test if the enviroment variable BOSSdir has been defined
#

if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

echo  " "
echo  "utility to separate concatenated .mol file"
echo  " "
$BOSSdir/miscexec/csmol
#
exit
