#!/bin/csh
set echo
#
# take mdl mol file to optimized BOSS Z-matrix
# with CM1A charges.
#
# usage:  xMOLZnob  moleculename
#
# file moleculename.mol must be in the directory
# file moleculename.z is created
# bond lengths are not optimized
# file optplta contains the PDB file of the optimized structure
#
# test if the enviroment variable BOSSdir has been defined
#
if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

$BOSSdir/autozmat -i mdl -z addbond,varangle,auto_addangle,vardihed,auto_adddihe
if (-e optzmat) rm optzmat
cp ${argv[1]}.z optzmat
csh $BOSSdir/scripts/AM1SPcmd >& log
rm optzmat
cp sum optzmat
csh $BOSSdir/scripts/OPTFcmd >& log
rm ${argv[1]}.z
cp sum ${argv[1]}.z
#
exit
