#!/bin/csh
#
# perform OPLS-AA optimization
# with Fletcher-Powell optimizer
echo  Fletcher-Powell optimization
#
# usage - xOPT moleculename
#
# test if the enviroment variable BOSSdir has been defined
#
if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

if (-e optzmat) rm optzmat
cp ${argv[1]}.z optzmat
csh $BOSSdir/scripts/OPTFcmd >& log
rm optzmat
echo  output is in out, sum and plt.pdb
grep "Optimized en" out
#
exit
