#!/bin/csh
#
echo  perform PM3 optimization
echo     include GB/SA
#
# usage - xPM3GBOPT moleculename
#
# test if the enviroment variable BOSSdir has been defined
#
if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

if (-e optzmat) rm optzmat
cp ${argv[1]}.z optzmat
csh $BOSSdir/scripts/PM3GBOPTcmd >& log
echo  output is in out, sum and plt.pdb
cp sum ${argv[1]}.pm3gb.z
rm optzmat
#
exit
