#!/bin/csh
#
echo  perform single-point PM3 calculation
echo  generate CM3 charges
#
# usage - xPM3CM3 moleculename
#
# test if the enviroment variable BOSSdir has been defined
#
if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

if (-e optzmat) rm optzmat
cp ${argv[1]}.z optzmat
csh $BOSSdir/scripts/PM3CM3cmd >& log
echo output is in out, sum and plt.pdb
#
exit
