"""LAMMPS input-file builders for ANI-based Green-Kubo viscosity simulations.

Two-stage workflow
------------------
1. **Equilibration** (``build_equil_input``):
   Langevin + NVE thermostat (= NVT ensemble).  Writes a restart file.

2. **Green-Kubo production** (``build_gk_input``):
   Pure NVE.  Uses ``fix ave/correlate`` to accumulate the running
   autocorrelation of the off-diagonal stress components
   (pxy, pxz, pyz) in LAMMPS *real* units (atm).

Important notes
---------------
* ``pyaev full`` is mandatory – CUAEV does not compute virial/stress.
* ``newton off`` is required for the standard (non-Kokkos) pair_ani.
* The ANI pair style identifies chemical elements from the Masses section
  of the data file, so ``pair_coeff * *`` takes no element arguments.
"""
from __future__ import annotations


# ──────────────────────────────────────────────────────────────────────────
# Shared formatting helper
# ──────────────────────────────────────────────────────────────────────────

def _pair_block(model_file: str, device: str, num_models: int) -> str:
    """Return the pair_style / pair_coeff block for ANI with pyaev."""
    return (
        f"pair_style      ani 5.1 {model_file} {device} {num_models} pyaev full single\n"
        f"pair_coeff      * *"
    )


# ──────────────────────────────────────────────────────────────────────────
# Stage 1: NVT equilibration
# ──────────────────────────────────────────────────────────────────────────

def build_equil_input(
    *,
    data_file: str,
    model_file: str,
    temperature: float,
    timestep_fs: float,
    nvt_steps: int,
    seed: int,
    device: str = "cuda",
    num_models: int = 1,
    restart_file: str = "equil_nvt.restart",
) -> str:
    """Generate a LAMMPS NVT-equilibration input for ANI viscosity.

    Parameters
    ----------
    data_file:
        Relative path to the LAMMPS data file (``system.data``).
    model_file:
        Absolute or relative path to the ANI TorchScript model (``ani2x.pt``).
    temperature:
        Target temperature in Kelvin.
    timestep_fs:
        Integration timestep in femtoseconds (0.5 fs recommended).
    nvt_steps:
        Number of NVT equilibration steps.
    seed:
        Random seed for velocity initialisation and Langevin thermostat.
    device:
        ``"cuda"`` or ``"cpu"``.
    num_models:
        Number of ensemble models (-1 = all; 1 = fastest).
    restart_file:
        Name of the restart file written at the end.

    Returns
    -------
    str
        Complete LAMMPS input text.
    """
    pair = _pair_block(model_file, device, num_models)
    return f"""\
# ================================================================
# LAMMPS Input: ANI NVT equilibration for viscosity workflow
# Generated by workflow/input_ani_viscosity.py
# Flow: system.data -> CG minimisation -> Langevin NVT -> restart
# ================================================================

units           real
atom_style      atomic
boundary        p p p

{pair}

read_data       {data_file}

neighbor        2.0 bin
neigh_modify    every 10 delay 0 check yes
newton          off

timestep        {timestep_fs:.6f}

variable        T    equal {temperature:.4f}
variable        seed equal {seed}

thermo          1000
thermo_style    custom step temp press vol density pe ke etotal
thermo_modify   flush yes

# ================================================================
# Stage 1: Energy minimisation
# ================================================================
min_style       cg
minimize        1.0e-6 1.0e-8 10000 100000
reset_timestep  0

# ================================================================
# Stage 2: NVT equilibration (Langevin + NVE)
# ================================================================
velocity        all create ${{T}} ${{seed}} rot yes mom yes dist gaussian

fix             f_lang all langevin ${{T}} ${{T}} 100.0 ${{seed}}
fix             f_nve  all nve

run             {nvt_steps}

unfix           f_lang
unfix           f_nve

write_restart   {restart_file}
"""


# ──────────────────────────────────────────────────────────────────────────
# Stage 2: NVE Green-Kubo production
# ──────────────────────────────────────────────────────────────────────────

def build_gk_input(
    *,
    restart_file: str,
    model_file: str,
    temperature: float,
    timestep_fs: float,
    prod_steps: int,
    corr_length: int,
    sample_every: int = 1,
    device: str = "cuda",
    num_models: int = 1,
    acf_file: str = "stress_acf.dat",
    thermo_file: str = "gk_thermo.dat",
) -> str:
    """Generate a LAMMPS NVE Green-Kubo production input for viscosity.

    The off-diagonal pressure components (pxy, pxz, pyz) are accumulated via
    ``fix ave/correlate`` with ``type auto ave running``.  This builds the
    running autocorrelation incrementally, so only the last block in the
    output file is needed for the final viscosity estimate.

    Output columns in *acf_file*::

        index  lag_time(fs)  ncount  acf_pxy  acf_pxz  acf_pyz

    Parameters
    ----------
    restart_file:
        Path to the equilibration restart file (relative to workdir).
    model_file:
        Path to the ANI TorchScript model.
    temperature:
        Simulation temperature in Kelvin (used only for thermo output).
    timestep_fs:
        Integration timestep in femtoseconds.
    prod_steps:
        Total number of NVE production steps.
    corr_length:
        Number of lag steps in the ACF (``Nrepeat`` in fix ave/correlate).
        Example: 40 000 steps × 0.5 fs = 20 ps correlation window.
    sample_every:
        Sample pressure every N steps (``Nevery`` in fix ave/correlate).
        Use 1 (every step) for best statistics.
    device, num_models:
        Forwarded to pair_style.
    acf_file:
        Output file for the stress ACF (input to analysis/viscosity.py).
    thermo_file:
        Output file for step/temp/press/vol (volume extracted later).

    Returns
    -------
    str
        Complete LAMMPS input text.
    """
    pair = _pair_block(model_file, device, num_models)
    # fix ave/correlate: Nfreq must be a multiple of Nevery.
    # With ave running, writing every corr_length steps gives good interim output.
    nfreq = sample_every * corr_length
    # Guard: nfreq must not exceed prod_steps.
    if nfreq > prod_steps:
        nfreq = prod_steps

    return f"""\
# ================================================================
# LAMMPS Input: ANI NVE Green-Kubo viscosity production
# Generated by workflow/input_ani_viscosity.py
# Flow: equil restart -> NVE + fix ave/correlate -> {acf_file}
# ================================================================

units           real
atom_style      atomic
boundary        p p p

read_restart    {restart_file}

{pair}

neighbor        2.0 bin
neigh_modify    every 10 delay 0 check yes
newton          off

timestep        {timestep_fs:.6f}

thermo          1000
thermo_style    custom step temp press vol density pe ke etotal
thermo_modify   flush yes

# ================================================================
# Green-Kubo production: NVE
# ================================================================
fix             f_nve all nve

# ── Off-diagonal pressure components (atm) ──────────────────────
variable        pxy equal pxy
variable        pxz equal pxz
variable        pyz equal pyz

# ── Thermo log: step temp press vol (for volume extraction) ─────
fix             thermo_log all print 1000 &
                "$(step) $(temp) $(press) $(vol)" &
                file {thermo_file} screen no &
                title "# step temp press vol"

# ── Stress autocorrelation (fix ave/correlate) ───────────────────
# Nevery={sample_every}  Nrepeat={corr_length}  Nfreq={nfreq}
# type auto  : each variable correlated with itself
# ave running: accumulates over all time origins seen so far
# Output columns: index  lag(fs)  ncount  acf_pxy  acf_pxz  acf_pyz
fix             stress_acf all ave/correlate &
                {sample_every} {corr_length} {nfreq} &
                v_pxy v_pxz v_pyz &
                type auto file {acf_file} ave running

run             {prod_steps}

unfix           f_nve
unfix           stress_acf
unfix           thermo_log
"""


__all__ = [
    "build_equil_input",
    "build_gk_input",
]
