"""LAMMPS input builders for BAMBOO Green-Kubo viscosity simulations."""
from __future__ import annotations

from collections.abc import Sequence


def _pair_style_line(pair_style_args: Sequence[float | int | str]) -> str:
    return "pair_style      bamboo " + " ".join(str(arg) for arg in pair_style_args)


def _pair_coeff_line(model_file: str, elements: Sequence[str]) -> str:
    return f"pair_coeff      {model_file}   " + " ".join(elements)


def _kspace_lines(
    *,
    pppm_accuracy: float,
    pppm_mesh: Sequence[int] | None,
) -> str:
    lines = [f"kspace_style    pppm {pppm_accuracy:.1e}"]
    if pppm_mesh:
        mesh = " ".join(str(int(value)) for value in pppm_mesh)
        lines.append(f"kspace_modify   mesh {mesh}")
    return "\n".join(lines)


def _forcefield_block(
    *,
    model_file: str,
    elements: Sequence[str],
    pair_style_args: Sequence[float | int | str],
    pppm_accuracy: float,
    pppm_mesh: Sequence[int] | None,
) -> str:
    return "\n".join(
        [
            _pair_style_line(pair_style_args),
            _pair_coeff_line(model_file, elements),
            "",
            _kspace_lines(pppm_accuracy=pppm_accuracy, pppm_mesh=pppm_mesh),
        ]
    )


def build_equil_input(
    *,
    data_file: str,
    model_file: str,
    elements: Sequence[str],
    pair_style_args: Sequence[float | int | str],
    pppm_accuracy: float,
    pppm_mesh: Sequence[int] | None,
    temperature: float,
    pressure_atm: float,
    timestep_fs: float,
    nvt_steps: int,
    npt_steps: int,
    final_nvt_steps: int,
    npt_thermo_file: str,
    seed: int,
    restart_file: str = "equil_nvt.restart",
    thermo_every: int = 1000,
    minimize: bool = True,
) -> str:
    """Generate the BAMBOO equilibration input used before NVE production."""
    forcefield = _forcefield_block(
        model_file=model_file,
        elements=elements,
        pair_style_args=pair_style_args,
        pppm_accuracy=pppm_accuracy,
        pppm_mesh=pppm_mesh,
    )
    minimize_block = ""
    if minimize:
        minimize_block = """\
# ================================================================
# Stage 1: Energy minimisation
# ================================================================
min_style       cg
minimize        1.0e-6 1.0e-8 10000 100000
reset_timestep  0

"""

    final_nvt_block = ""
    if final_nvt_steps > 0:
        final_nvt_block = f"""\
# ================================================================
# Stage 4: short NVT settling before NVE production
# ================================================================
fix             f_nvt_settle all nvt temp ${{T}} ${{T}} 100.0
fix             f_equil_tail all print {thermo_every} "$(step) $(temp) $(v_rho_trace)" append {npt_thermo_file} screen no

run             {final_nvt_steps}

unfix           f_nvt_settle
unfix           f_equil_tail

"""

    return f"""\
# ================================================================
# LAMMPS Input: BAMBOO equilibration for viscosity workflow
# Generated by workflow/input_viscosity.py
# Flow: in.data -> minimisation -> NVT -> isotropic NPT -> short NVT -> restart
# ================================================================

units           real
atom_style      full
atom_modify     map yes
boundary        p p p

newton          off
read_data       {data_file}

{forcefield}

neighbor        3.0 bin
neigh_modify    every 1 delay 0 check yes

timestep        {timestep_fs:.6f}

variable        T    equal {temperature:.4f}
variable        P    equal {pressure_atm:.4f}
variable        seed equal {seed}

thermo          {thermo_every}
thermo_style    custom step temp press vol density pe ke etotal evdwl ecoul spcpu
thermo_modify   flush yes

{minimize_block}\
# ================================================================
# Stage 2: short NVT warmup
# ================================================================
velocity        all create ${{T}} ${{seed}} rot yes mom yes dist gaussian
velocity        all zero linear

fix             f_nvt_warm all nvt temp ${{T}} ${{T}} 100.0

run             {nvt_steps}

unfix           f_nvt_warm

# ================================================================
# Stage 3: isotropic NPT density equilibration
# ================================================================
variable        rho_trace equal density
fix             f_npt all npt temp ${{T}} ${{T}} 100.0 iso ${{P}} ${{P}} 1000.0 drag 2.0
fix             f_npt_rho all print {thermo_every} "$(step) $(temp) $(v_rho_trace)" file {npt_thermo_file} screen no &
                title "# step temp_K density_g_cm3"

run             {npt_steps}

unfix           f_npt
unfix           f_npt_rho

{final_nvt_block}\
write_restart   {restart_file}
"""


def build_gk_input(
    *,
    restart_file: str,
    model_file: str,
    elements: Sequence[str],
    pair_style_args: Sequence[float | int | str],
    pppm_accuracy: float,
    pppm_mesh: Sequence[int] | None,
    temperature: float,
    timestep_fs: float,
    prod_steps: int,
    corr_length: int,
    sample_every: int = 1,
    acf_file: str = "stress_acf.dat",
    pressure_file: str | None = "pressure_tensor.dat",
    pressure_every: int | None = None,
    thermo_file: str = "gk_thermo.dat",
    thermo_every: int = 1000,
) -> str:
    """Generate the BAMBOO NVE Green-Kubo production input."""
    forcefield = _forcefield_block(
        model_file=model_file,
        elements=elements,
        pair_style_args=pair_style_args,
        pppm_accuracy=pppm_accuracy,
        pppm_mesh=pppm_mesh,
    )
    nfreq = sample_every * corr_length
    if nfreq > prod_steps:
        nfreq = prod_steps
    if pressure_every is None:
        pressure_every = sample_every
    if pressure_every <= 0:
        raise ValueError("pressure_every must be positive")

    pressure_log_block = ""
    pressure_unfix = ""
    if pressure_file:
        pressure_log_block = f"""\
fix             pressure_log all print {pressure_every} &
                "$(step) $(v_pxy) $(v_pxz) $(v_pyz)" &
                file {pressure_file} screen no &
                title "# step pxy pxz pyz"

"""
        pressure_unfix = "unfix           pressure_log\n"

    return f"""\
# ================================================================
# LAMMPS Input: BAMBOO NVE Green-Kubo viscosity production
# Generated by workflow/input_viscosity.py
# Flow: equil restart -> NVE + stress traces -> viscosity analysis
# ================================================================

units           real
atom_style      full
atom_modify     map yes
boundary        p p p

newton          off
read_restart    {restart_file}

{forcefield}

neighbor        3.0 bin
neigh_modify    every 1 delay 0 check yes

timestep        {timestep_fs:.6f}

variable        T equal {temperature:.4f}

thermo          {thermo_every}
thermo_style    custom step temp press vol density pe ke etotal evdwl ecoul spcpu
thermo_modify   flush yes

# ================================================================
# Green-Kubo production: NVE
# ================================================================
fix             f_nve all nve

variable        pxy equal pxy
variable        pxz equal pxz
variable        pyz equal pyz

fix             thermo_log all print {thermo_every} &
                "$(step) $(temp) $(press) $(vol)" &
                file {thermo_file} screen no &
                title "# step temp press vol"

{pressure_log_block}\
# Nevery={sample_every}  Nrepeat={corr_length}  Nfreq={nfreq}
# Output columns: index  lag(fs)  ncount  acf_pxy  acf_pxz  acf_pyz
fix             stress_acf all ave/correlate &
                {sample_every} {corr_length} {nfreq} &
                v_pxy v_pxz v_pyz &
                type auto file {acf_file} ave running

run             {prod_steps}

unfix           f_nve
unfix           stress_acf
{pressure_unfix}\
unfix           thermo_log
"""


__all__ = [
    "build_equil_input",
    "build_gk_input",
]
