#!/bin/csh
set echo
#
# script to run a MC simulation for a slab     
#
# usage:  xSLAB725 moleculename
# or to run in background: xSLAB725 moleculename &
#
# make subdirectory
#
mkdir $argv[1]
cd $argv[1]
#
# moleculename.z is copied from above           
#
cp ../${argv[1]}.z slzmat      
cp ../sl725cmd .
cp ../sl725par .
# execute MC
csh sl725cmd >& log
cd ..
#
exit
