#!/bin/csh
set echo
#
#            Queue Version:
# script to run an FEP job on the PC cluster   
#
# usage:           xFEPQ  name-of-Zmatrix (.z excluded)
# multiple files:  xMANY filenames xFEPQ
# 
# Files fepcmd feppar0 feppar slvzmat need to be in the submitting directory.
# Output is in ${argv[1]}.fep (name-of-Zmatrix.fep).
#
# make subdirectory
#
mkdir ${argv[1]}.fep
cd ${argv[1]}.fep
#
# name-of-Zmatrix is in the current directory
#
cp ../${argv[1]}.z ./fepzmat
cp ../fepcmd .
cp ../feppar0 .
cp ../feppar .
cp ../slvzmat .
#
# execute MC
#
# set-up for transfer to queue
cd ..
cat <<EOF  > ${argv[1]}.q
hostname

# set variables to hold names of:
set OD = \$DQS_O_WORKDIR                   # Original Directory
set LD = /scratch/bill/\$JOB_ID            # Local Directory
set JN = \$JOB_NAME:r                      # Job name
set JN = \$JN.fep
set AN = \$JN.tar                          # Archive name

cd \$OD/\$JN                               # Create the archive, compress it
tar cf ../\$AN *
cd ..
gzip -9 \$AN

mkdir \$LD                                 # Create local directory, copy archive
/bin/cp \$AN.gz \$LD                       #    to it, remove original
/bin/rm \$AN.gz

cd \$LD                                    # Go to local directory, unpack and
gzip -cd \$AN.gz | tar xof -               #    remove archive
/bin/rm \$AN.gz

csh fepcmd                                 # run

tar cf ../\$AN f*                          # Create output archive, compress
cd ..                                      #   it and move to Original
gzip -9 \$AN                               #   directory, remove Local
/bin/rm -rf \$LD:t                         #   directory.
/bin/cp \$AN.gz \$OD/\$JN
/bin/rm \$AN.gz
cd \$OD/\$JN
gzip -cd \$AN.gz | tar xf -
/bin/rm \$AN.gz
EOF
q -i ${argv[1]}.q                          # Submit job to queue
exit
