#!/bin/csh
set echo
#
# script to run a standard linear response job
# using the OPLS-AA force field
#
# usage:  xLRAA moleculename
# or to run in background: xLRAA moleculename &
#
# make subdirectory
mkdir $argv[1]
cd $argv[1]
# moleculename.z is copied from the molecules/smallarea
cp $BOSSdir/molecules/small/${argv[1]}.z lrzmat
cp $BOSSdir/testjobs/linres/lrcmd .
cp $BOSSdir/testjobs/linres/lrpar .
# execute
csh lrcmd >& log
rm lrpar
rm *a *b *c *otd *pltd *sv* *eq
# compute properties
$BOSSdir/miscexec/PROPAA
cd ..
#
exit
