#!/bin/csh
#
echo  perform OPLS-AA optimization
echo  for structure with rc = 1.0
#
# usage - xOPT moleculename
#
# test if the enviroment variable BOSSdir has been defined
#
if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

if (-e optzmat) rm optzmat
cp ${argv[1]}.z optzmat
csh $BOSSdir/scripts/OPT1cmd >& log
rm optzmat
echo  output is in out, sum and plt.pdb
#
exit
