"""LAMMPS atomic data file builder for ANI pair style.

Converts a Packmol XYZ output to a LAMMPS data file using the ``atomic``
atom style (no bonds, angles, or charges).  Element identification by ANI
is done via atomic masses in the Masses section, so pair_coeff needs no
element symbols – just ``pair_coeff * *``.
"""
from __future__ import annotations

from pathlib import Path

# ANI-2x supported elements and their standard atomic masses (g/mol).
ANI_ELEMENTS: list[str] = ["H", "C", "N", "O", "S", "F", "Cl"]

_MASSES: dict[str, float] = {
    "H":  1.008,
    "C": 12.011,
    "N": 14.007,
    "O": 15.999,
    "S": 32.06,
    "F": 18.998,
    "Cl": 35.45,
}


class AniDataBuilder:
    """Convert a Packmol XYZ file to a LAMMPS data file for ANI simulations.

    Atom types are numbered in ANI element order (H=1, C=2, …) for only the
    elements actually present in the system.  The Masses section encodes the
    standard atomic masses so the pair_ani plugin can identify element species.

    Usage
    -----
    >>> builder = AniDataBuilder()
    >>> data_path = builder.build("system.xyz", (30.0, 30.0, 30.0), "system.data")
    """

    def build(
        self,
        system_xyz: str | Path,
        box_lengths: tuple[float, float, float],
        output: str | Path,
    ) -> Path:
        """Read a Packmol XYZ file and write a LAMMPS atomic data file.

        Parameters
        ----------
        system_xyz:
            Path to the XYZ file produced by Packmol.
        box_lengths:
            ``(Lx, Ly, Lz)`` box dimensions in Ångström.  The box origin is
            placed at (0, 0, 0) and is orthorhombic.
        output:
            Destination path for the LAMMPS data file.

        Returns
        -------
        Path
            Absolute path to the written data file.
        """
        atoms = self._read_xyz(Path(system_xyz))
        out = Path(output)
        out.parent.mkdir(parents=True, exist_ok=True)
        self._write_data(atoms, box_lengths, out)
        return out.resolve()

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _read_xyz(
        xyz: Path,
    ) -> list[tuple[str, float, float, float]]:
        """Parse XYZ file and return list of (element, x, y, z)."""
        with open(xyz) as fh:
            lines = fh.readlines()

        n_declared = int(lines[0].strip())
        # Line 1 is the comment/title line – skip it.
        atoms: list[tuple[str, float, float, float]] = []
        for raw in lines[2 : 2 + n_declared]:
            parts = raw.split()
            if len(parts) < 4:
                continue
            elem = parts[0].capitalize()
            if elem not in _MASSES:
                raise ValueError(
                    f"Element '{elem}' in {xyz} is not supported by ANI-2x. "
                    f"Supported elements: {ANI_ELEMENTS}"
                )
            atoms.append((elem, float(parts[1]), float(parts[2]), float(parts[3])))

        if len(atoms) != n_declared:
            raise ValueError(
                f"{xyz} declares {n_declared} atoms but {len(atoms)} were parsed."
            )
        return atoms

    @staticmethod
    def _write_data(
        atoms: list[tuple[str, float, float, float]],
        box_lengths: tuple[float, float, float],
        output: Path,
    ) -> None:
        """Write LAMMPS atomic data file."""
        # Only include elements that actually appear, preserving ANI order.
        present = {elem for elem, *_ in atoms}
        used_elements = [el for el in ANI_ELEMENTS if el in present]
        type_map = {el: i + 1 for i, el in enumerate(used_elements)}

        Lx, Ly, Lz = box_lengths
        lines: list[str] = [
            "# LAMMPS data file – generated by AniDataBuilder (core/data_builder.py)",
            "",
            f"{len(atoms)} atoms",
            f"{len(used_elements)} atom types",
            "",
            f"0.0 {Lx:.6f} xlo xhi",
            f"0.0 {Ly:.6f} ylo yhi",
            f"0.0 {Lz:.6f} zlo zhi",
            "",
            "Masses",
            "",
        ]
        for el in used_elements:
            lines.append(f"  {type_map[el]}  {_MASSES[el]:.4f}  # {el}")

        lines += ["", "Atoms # atomic", ""]
        for idx, (elem, x, y, z) in enumerate(atoms, start=1):
            lines.append(f"  {idx}  {type_map[elem]}  {x:.6f}  {y:.6f}  {z:.6f}")

        output.write_text("\n".join(lines) + "\n")


__all__ = ["AniDataBuilder", "ANI_ELEMENTS"]
