      UA ethyl methyl ether                                 Tot. E =      0.1153
   1 O    108    0    0    0.000000   0    0.000000   0    0.000000        0
   2 DUM   -1    0    1    0.500000   0    0.000000   0    0.000000        0
   3 DUM   -1    0    2    0.500000   1   90.000000   0    0.000000        0
   4 CH3  109    0    1    1.426560   2   90.000000   3  180.000000        0
   5 CH2  110    0    1    1.426107   4  111.947836   2  180.000000        0
   6 CH3   68    0    5    1.527891   1  109.719014   4  179.999998        0
                    Geometry Variations follow                                  
                    Variable Bonds follow         (I4 or I4-I4)                 
0004-0006                                                                       
                    Additional Bonds follow       (2I4)                         
                    Harmonic Constraints follow                                 
                    Variable Bond Angles follow   (I4 or I4-I4)                 
0005-0006                                                                       
                    Additional Bond Angles follow (3I4)                         
                    Variable Dihedrals follow     (3I4,F12.6)                   
0006-0006                                                                       
                    Additional Dihedrals follow   (6I4)                         
                    Domain Definitions follow     (4I4)                         
                    Final blank line                                            
