#!/bin/csh
set echo
#
# perform OPLS-UA optimization
#
# usage - xOPTUA moleculename
#
# test if the enviroment variable BOSSdir has been defined
#
if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

if (-e optzmat) rm optzmat
cp ${argv[1]}.z optzmat
csh $BOSSdir/scripts/OPTUAcmd >& log
grep "Optimized en" out
#
exit
