#!/bin/csh
#
# perform OPLS-AA optimization
echo  OPLS-AA with GB/SA optimization - BFGS
#
# usage - xOPTGB moleculename
#
# test if the enviroment variable BOSSdir has been defined
#
if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

if (-e optzmat) rm optzmat
cp ${argv[1]}.z optzmat
csh $BOSSdir/scripts/OPTGBcmd >& log
rm optzmat
echo  output is in out, sum and plt.pdb
grep "G pol" out
grep "G SASA" out
grep "Total GB/SA" out
grep "Total Ener" out
#
exit
