#!/bin/csh
set echo
#
# take pdb file to optimized BOSS Z-matrix
# with CM1A charges
#
# usage:  xPDBZ+  moleculename
#
# file moleculename.pdb must be in the directory
# file moleculename.z is created
# file plt.pdb contains the PDB file of the optimized structure
#
# test if the enviroment variable BOSSdir has been defined
#
if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

$BOSSdir/autozmat -i pdb -z default <${argv[1]}.pdb >${argv[1]}.z
if (-e optzmat) rm optzmat
cp ${argv[1]}.z optzmat
csh $BOSSdir/scripts/AM1SP+cmd >& log
rm optzmat
cp sum optzmat
csh $BOSSdir/scripts/OPTFcmd >& log
rm optzmat
cp sum optzmat
csh $BOSSdir/scripts/AM1SP+cmd >& log
rm optzmat
cp sum optzmat
csh $BOSSdir/scripts/OPTFcmd >& log

rm ${argv[1]}.z
cp sum ${argv[1]}.z
#
exit
