#!/bin/csh
#
echo  perform PM3 optimization for cation
#
# usage - xPM3OPT+ moleculename
#
# test if the enviroment variable BOSSdir has been defined
#
if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

if (-e optzmat) rm optzmat
cp ${argv[1]}.z optzmat
csh $BOSSdir/scripts/PM3OPT+cmd >& log
rm optzmat
echo  output is in out, sum and plt.pdb
#
exit
