#!/bin/csh
#
echo  run FEPs to compute delG hydration
#
# usage - xDGHYD moleculename
#
# test if the enviroment variable BOSSdir has been defined
#
if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

mkdir $argv[1]
cd $argv[1]

# make zmats for Q and LJ FEPs
cp $BOSSdir/molecules/OPLS2020/${argv[1]}.z optzmat
csh $BOSSdir/scripts/ZQFEPcmd >& log
ren sum Q.z
csh $BOSSdir/scripts/ZLJFEPcmd >& log
ren sum LJ.z

# run 4 FEPS with 20 windows each
# gas averaging is 2M per window
# aq Q  averaging is 200M per window
# aq LJ averaging is 500M per window
../xFEPGAS20fQ Q
../xFEPGAS20bQ LJ
../xFEP200f20Q Q
../xFEP500b20Q LJ
rm log out optzmat

#
exit
