#!/bin/csh
set echo
#
# perform single-point OPLS-AA calculation
# and create a mol file in moleculename.mol
#
# usage - xZmol moleculename
#
# test if the enviroment variable BOSSdir has been defined
#
if (!($?BOSSdir)) then
   echo "BOSSdir has not been defined; please see README"
   exit (-1)
endif

if (-e optzmat) rm optzmat
cp ${argv[1]}.z optzmat
csh $BOSSdir/scripts/Zmolcmd >& log
if (-e ${argv[1]}.mol) rm ${argv[1]}.mol
cp plt.pdb ${argv[1]}.mol
#
exit
